// Mocks generated by Mockito 5.4.6 from annotations
// in mpv_ioc/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i22;
import 'dart:typed_data' as _i24;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter/widgets.dart' as _i3;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;
import 'package:mpv_ioc/core/api/exception/failure.dart' as _i8;
import 'package:mpv_ioc/core/api/network/network_info.dart' as _i5;
import 'package:mpv_ioc/core/api/responses/api_response.dart' as _i9;
import 'package:mpv_ioc/core/api/services/api_client.dart' as _i7;
import 'package:mpv_ioc/core/api/services/api_services.dart' as _i11;
import 'package:mpv_ioc/core/data/events/message_event.dart' as _i16;
import 'package:mpv_ioc/core/data/events/nav_event.dart' as _i15;
import 'package:mpv_ioc/core/data/models/post.dart' as _i12;
import 'package:mpv_ioc/core/enums/enums.dart' as _i10;
import 'package:mpv_ioc/core/helpers/widget_helper.dart' as _i21;
import 'package:mpv_ioc/core/routes/app_router.dart' as _i13;
import 'package:mpv_ioc/core/storage/cache/cache_storage.dart' as _i17;
import 'package:mpv_ioc/core/storage/database/database_storage.dart' as _i18;
import 'package:mpv_ioc/core/utils/navigation_service.dart' as _i14;
import 'package:mpv_ioc/features/post_detail/repository/post_detail_repository.dart'
    as _i20;
import 'package:mpv_ioc/features/posts/repository/posts_repository.dart'
    as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouterConfig_1<T> extends _i1.SmartFake
    implements _i3.RouterConfig<T> {
  _FakeRouterConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [IApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIApiClient extends _i1.Mock implements _i7.IApiClient {
  MockIApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<T>>> request<T>(
    String? url,
    _i10.MethodType? method,
    T Function(dynamic)? fromJson,
    dynamic params, {
    Map<String, dynamic>? queryParameters,
    dynamic interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url, method, fromJson, params],
              {#queryParameters: queryParameters, #interceptor: interceptor},
            ),
            returnValue:
                _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<T>>>.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<T>>(
                    this,
                    Invocation.method(
                      #request,
                      [url, method, fromJson, params],
                      {
                        #queryParameters: queryParameters,
                        #interceptor: interceptor,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<T>>>);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<T>>> multipartRequest<T>(
    String? url,
    _i10.MethodType? method,
    T Function(dynamic)? fromJson,
    dynamic params, {
    Map<String, dynamic>? queryParameters,
    dynamic interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #multipartRequest,
              [url, method, fromJson, params],
              {#queryParameters: queryParameters, #interceptor: interceptor},
            ),
            returnValue:
                _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<T>>>.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<T>>(
                    this,
                    Invocation.method(
                      #multipartRequest,
                      [url, method, fromJson, params],
                      {
                        #queryParameters: queryParameters,
                        #interceptor: interceptor,
                      },
                    ),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<T>>>);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i11.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<List<_i12.Post>>>>
  getPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, []),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<List<_i12.Post>>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<List<_i12.Post>>>(
                    this,
                    Invocation.method(#getPosts, []),
                  ),
                ),
          )
          as _i6.Future<
            _i2.Either<_i8.Failure, _i9.ApiResponse<List<_i12.Post>>>
          >);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>> getPost(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [id]),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<_i12.Post>>(
                    this,
                    Invocation.method(#getPost, [id]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>>);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>> createPost({
    required String? title,
    required String? body,
    required int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #title: title,
              #body: body,
              #userId: userId,
            }),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<_i12.Post>>(
                    this,
                    Invocation.method(#createPost, [], {
                      #title: title,
                      #body: body,
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>>);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>> updatePost({
    required int? id,
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [], {
              #id: id,
              #title: title,
              #body: body,
            }),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<_i12.Post>>(
                    this,
                    Invocation.method(#updatePost, [], {
                      #id: id,
                      #title: title,
                      #body: body,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>>);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<void>>> deletePost(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [id]),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<void>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<void>>(
                    this,
                    Invocation.method(#deletePost, [id]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<void>>>);
}

/// A class which mocks [IAppRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAppRouter extends _i1.Mock implements _i13.IAppRouter {
  MockIAppRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RouterConfig<Object> get routerConfig =>
      (super.noSuchMethod(
            Invocation.getter(#routerConfig),
            returnValue: _FakeRouterConfig_1<Object>(
              this,
              Invocation.getter(#routerConfig),
            ),
          )
          as _i3.RouterConfig<Object>);

  @override
  void navigate(
    String? name, {
    required _i3.BuildContext? context,
    Map<String, String>? pathParameters = const {},
    Map<String, String>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #navigate,
      [name],
      {
        #context: context,
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<T?> push<T>(
    String? name, {
    required _i3.BuildContext? context,
    Map<String, String>? pathParameters = const {},
    Map<String, String>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #push,
              [name],
              {
                #context: context,
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
                #fragment: fragment,
              },
            ),
            returnValue: _i6.Future<T?>.value(),
          )
          as _i6.Future<T?>);

  @override
  void replace(
    String? name, {
    required _i3.BuildContext? context,
    Map<String, String>? pathParameters = const {},
    Map<String, String>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #replace,
      [name],
      {
        #context: context,
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void pop(_i3.BuildContext? context, [Object? result]) => super.noSuchMethod(
    Invocation.method(#pop, [context, result]),
    returnValueForMissingStub: null,
  );

  @override
  bool canPop(_i3.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#canPop, [context]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i14.NavigationService {
  MockNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i15.NavEvent> get navigationStream =>
      (super.noSuchMethod(
            Invocation.getter(#navigationStream),
            returnValue: _i6.Stream<_i15.NavEvent>.empty(),
          )
          as _i6.Stream<_i15.NavEvent>);

  @override
  _i6.Stream<_i16.MessageEvent> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i6.Stream<_i16.MessageEvent>.empty(),
          )
          as _i6.Stream<_i16.MessageEvent>);

  @override
  void navigateTo(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, String>? queryParameters = const {},
    Object? extra,
    String? fragment,
    _i10.RouteType? routeType = _i10.RouteType.named,
    _i10.RouteLevel? routeLevel = _i10.RouteLevel.normal,
  }) => super.noSuchMethod(
    Invocation.method(
      #navigateTo,
      [name],
      {
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
        #routeType: routeType,
        #routeLevel: routeLevel,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void showMessage(_i16.MessageEvent? event) => super.noSuchMethod(
    Invocation.method(#showMessage, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CacheStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheStorage extends _i1.Mock implements _i17.CacheStorage {
  MockCacheStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool?> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);

  @override
  _i6.Future<void> setLoggedIn(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setLoggedIn, [status]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<bool?> getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i6.Future<bool?>.value(),
          )
          as _i6.Future<bool?>);

  @override
  _i6.Future<void> setThemeMode(bool? isDark) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [isDark]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DatabaseStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseStorage extends _i1.Mock implements _i18.DatabaseStorage {
  MockDatabaseStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveDraft(Map<String, dynamic>? post) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [post]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getDrafts() =>
      (super.noSuchMethod(
            Invocation.method(#getDrafts, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> deleteDraft(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDraft, [localId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearDrafts() =>
      (super.noSuchMethod(
            Invocation.method(#clearDrafts, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [PostsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsRepository extends _i1.Mock implements _i19.PostsRepository {
  MockPostsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<List<_i12.Post>>>>
  getPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, []),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<List<_i12.Post>>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<List<_i12.Post>>>(
                    this,
                    Invocation.method(#getPosts, []),
                  ),
                ),
          )
          as _i6.Future<
            _i2.Either<_i8.Failure, _i9.ApiResponse<List<_i12.Post>>>
          >);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>> getPost(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [id]),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<_i12.Post>>(
                    this,
                    Invocation.method(#getPost, [id]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>>);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>> createPost({
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {#title: title, #body: body}),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<_i12.Post>>(
                    this,
                    Invocation.method(#createPost, [], {
                      #title: title,
                      #body: body,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>>);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>> updatePost({
    required int? id,
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [], {
              #id: id,
              #title: title,
              #body: body,
            }),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<_i12.Post>>(
                    this,
                    Invocation.method(#updatePost, [], {
                      #id: id,
                      #title: title,
                      #body: body,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>>);

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<void>>> deletePost(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [id]),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<void>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<void>>(
                    this,
                    Invocation.method(#deletePost, [id]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<void>>>);
}

/// A class which mocks [PostDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostDetailRepository extends _i1.Mock
    implements _i20.PostDetailRepository {
  MockPostDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>> getPost(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [id]),
            returnValue:
                _i6.Future<
                  _i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>
                >.value(
                  _FakeEither_0<_i8.Failure, _i9.ApiResponse<_i12.Post>>(
                    this,
                    Invocation.method(#getPost, [id]),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i8.Failure, _i9.ApiResponse<_i12.Post>>>);
}

/// A class which mocks [IWidgetHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWidgetHelper extends _i1.Mock implements _i21.IWidgetHelper {
  MockIWidgetHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showToast({
    _i3.BuildContext? context,
    String? titleLabel,
    String? subTitleLabel,
  }) => super.noSuchMethod(
    Invocation.method(#showToast, [], {
      #context: context,
      #titleLabel: titleLabel,
      #subTitleLabel: subTitleLabel,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void showToastError({_i3.BuildContext? context, required String? message}) =>
      super.noSuchMethod(
        Invocation.method(#showToastError, [], {
          #context: context,
          #message: message,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void showToastSuccess({
    _i3.BuildContext? context,
    required String? message,
  }) => super.noSuchMethod(
    Invocation.method(#showToastSuccess, [], {
      #context: context,
      #message: message,
    }),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i22.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i22.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i22.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i22.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i6.Future<String>.value(
              _i23.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i24.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i6.Future<_i24.Uint8List>.value(_i24.Uint8List(0)),
          )
          as _i6.Future<_i24.Uint8List>);

  @override
  _i6.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i6.Future<_i4.StreamedResponse>.value(
              _FakeStreamedResponse_3(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
